# Generated by Django 3.1.6 on 2021-02-09 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_madlib_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='madlib',
            name='user',
        ),
    ]
