# Generated by Django 3.1.6 on 2021-02-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_madlib_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='madlib',
            name='story',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
