# Generated by Django 3.1.6 on 2021-02-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20210209_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='madlib',
            name='story',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
