# Generated by Django 3.1.6 on 2021-02-09 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_storywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='storywords',
            name='madlib',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.madlib'),
        ),
    ]
