# Generated by Django 3.1.6 on 2021-02-09 23:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_storywords_madlib'),
    ]

    operations = [
        migrations.AlterField(
            model_name='madlib',
            name='wordinserts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), null=True, size=None),
        ),
        migrations.DeleteModel(
            name='StoryWords',
        ),
    ]
